platform :ios,'9.0'
pod 'AFNetworking'
pod 'YYModel'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'RESideMenu'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'CHTCollectionViewWaterfallLayout'
pod 'ASProgressPopUpView'
pod 'ASValueTrackingSlider'

